#ifndef COMMONS_H
#define COMMONS_H

typedef int EXIT_CODE;

#define MAX_NAME_LENGTH 20
#define NUM_OF_ROOMS 5
#define NUM_OF_GUESTS 15
#define TRUE 1
#define FALSE 0

typedef enum {
	TG_SUCCESS,
	TG_THREADS_WAIT_FAILED,
	TG_FILE_OPEN_FAILED,
	TG_THREAD_PARAMS_NULL,
	TG_THREAD_CREATE_FAILED,
	TG_MUTEX_CREATE_FAILED,
	TG_MUTEX_ABANDONED,
	TG_MUTEX_WAIT_FAILED,
	TG_MUTEX_RELEASE_FAILED,
	TG_NOT_ENOUGH_COMMAND_LINE_ARGUMENTS
} EXIT_CODES;

#endif