#ifndef COMMONS_H
#define COMMONS_H

typedef int EXIT_CODE;

#define MAX_NAME_LENGTH 20
#define NUM_OF_ROOMS 5
#define NUM_OF_GUESTS 15
#define MAX_LINE_LENGTH 256
#define TRUE 1
#define FALSE 0

typedef enum {
	NONE,
	GUEST_WAITING,
	GUEST_IN,
	GUEST_OUT
} GUEST_STATUS;

typedef enum {
	HM_SUCCESS,
	HM_THREADS_WAIT_FAILED,
	HM_FILE_OPEN_FAILED,
	HM_THREAD_PARAMS_NULL,
	HM_THREAD_CREATE_FAILED,
	HM_MUTEX_CREATE_FAILED,
	HM_MUTEX_ABANDONED,
	HM_MUTEX_WAIT_FAILED,
	HM_MUTEX_RELEASE_FAILED,
	HM_SEMAPHORE_CREATE_FAILED,
	HM_NOT_ENOUGH_COMMAND_LINE_ARGUMENTS
} EXIT_CODES;

static const char *LOG_FILE_NAME = "roomLog.txt";

#endif